import { Subscription } from '../subscription.js';

/**
 * Object receiving data from an observable.
 */
export interface Observer<in D = unknown> {
  /**
   * Called with subscription generated by subscribe calls.
   * @param subscription
   */
  readonly start?: (subscription: Subscription) => void;

  /**
   * Called with each emitted value
   * @param data
   */
  next(data: D): void;

  /**
   * Called when an error occurs in the observable
   * @param err
   */
  error(err: unknown): void;

  /**
   * Called when the observable completes. No other data or error will then be received.
   */
  complete(): void;
}
